[task_config]
includes = ["bin"]

[tools]
"cargo:cargo-audit" = "latest"
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-sort" = "latest"
"cargo:taplo-cli" = "latest"
"cargo:cargo-workspace" = "latest"
"npm:editorconfig-checker" = "latest"
"npm:markdownlint-cli" = "latest"
pipx = "latest"
rust = { version = "nightly", components = "clippy,llvm-tools-preview,rustfmt,rust-src", targets = "x86_64-unknown-linux-gnu,x86_64-pc-windows-gnu,x86_64-apple-darwin,aarch64-apple-darwin" }
shellcheck = "latest"
yamllint = "latest"
